/**
 * Peekaboo CLI — bootstrap a new installation.
 *
 * Usage:
 *   npx peekaboo init [app-name]
 *   node dist/cli.js init [app-name]
 */

import { randomBytes, randomUUID } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { hashSync } from 'bcryptjs';
import { getDb } from './db/db.js';

export interface InitResult {
  secret: string;
  apiKey: string;
  dbPath: string;
  configPath: string;
  envPath: string;
}

export interface InitOptions {
  appName?: string;
  port?: number;
}

/**
 * Bootstrap a new Peekaboo installation.
 *
 * Generates a master secret, writes .env and hub-config.yaml,
 * initializes the database, and creates the first API key.
 *
 * @param targetDir - Directory to initialize in (defaults to cwd)
 * @param options - Optional overrides
 */
export function init(targetDir?: string, options?: InitOptions): InitResult {
  const dir = targetDir ?? process.cwd();
  const envPath = resolve(dir, '.env');
  const configPath = resolve(dir, 'hub-config.yaml');
  const dbPath = resolve(dir, 'peekaboo.db');

  // Guard against re-initialization
  if (existsSync(envPath)) {
    throw new Error(`.env already exists at ${envPath}. Delete it first to re-initialize.`);
  }

  // Generate master secret
  const secret = randomBytes(32).toString('base64');

  // Write .env
  writeFileSync(envPath, `PEEKABOO_SECRET=${secret}\n`, 'utf-8');

  // Write minimal hub-config.yaml
  const port = options?.port ?? 3000;
  const configContent = [
    '# Peekaboo Hub Configuration',
    '# Generated by: npx peekaboo init',
    '#',
    `# Connect data sources through the GUI at http://localhost:${port}`,
    '',
    'sources: {}',
    '',
    `port: ${port}`,
    '',
  ].join('\n');
  writeFileSync(configPath, configContent, 'utf-8');

  // Initialize database
  const db = getDb(dbPath);

  // Generate API key
  const appName = options?.appName ?? 'default';
  const id = appName.toLowerCase().replace(/\s+/g, '-');
  const rawKey = `pk_${randomUUID().replace(/-/g, '')}`;
  const keyHash = hashSync(rawKey, 10);
  db.prepare(
    'INSERT INTO api_keys (id, key_hash, name, allowed_manifests) VALUES (?, ?, ?, ?)',
  ).run(id, keyHash, appName, JSON.stringify(['*']));

  db.close();

  return { secret, apiKey: rawKey, dbPath, configPath, envPath };
}

// --- CLI runner (only executes when this file is the entry point) ---
const isDirectRun = process.argv[1]?.endsWith('cli.js') || process.argv[1]?.endsWith('cli.ts');

if (isDirectRun) {
  const command = process.argv[2];

  if (command === 'init') {
    const appName = process.argv[3] ?? 'default';
    try {
      const result = init(undefined, { appName });
      console.log('\n  Peekaboo initialized successfully!\n');
      console.log(`  .env created            ${result.envPath}`);
      console.log(`  hub-config.yaml created  ${result.configPath}`);
      console.log(`  Database created         ${result.dbPath}`);
      console.log(`\n  API Key (save this — shown only once):`);
      console.log(`    ${result.apiKey}\n`);
      console.log('  Next steps:');
      console.log('    1. Start the server:  node dist/index.js');
      console.log('    2. Open the GUI:      http://localhost:3000');
      console.log('    3. Connect sources and configure access policies\n');
    } catch (err) {
      console.error(`Error: ${(err as Error).message}`);
      process.exit(1);
    }
  } else {
    console.log('Peekaboo CLI v0.1.0');
    console.log('\nUsage:');
    console.log('  npx peekaboo init [app-name]   Bootstrap a new Peekaboo installation');
  }
}
